name: Java CI com Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: mvn compile

      - name: Rodar testes
        run: mvn test

      - name: Finalizado com sucesso
        run: echo "✅ Build e testes finalizados com sucesso"
